name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin --bundles app'
            arch: 'aarch64'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin --bundles app'
            arch: 'x86_64'
          - platform: 'windows-2025'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm ci

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_UPDATER_SUFFIX: "-${{ matrix.arch }}"
        with:
          tagName: v__VERSION__ # the action automatically replaces __VERSION__ with the app version.
          releaseName: 'v__VERSION__'
          releaseBody: |
            ## What's Changed

            See the assets below to download this version and install.

            ### Installation Notes

            **macOS**: Download the `.app` file for your architecture:
            - `presto_x.x.x_aarch64.app.tar.gz` for Apple Silicon (M1/M2/M3 Macs)
            - `presto_x.x.x_x64.app.tar.gz` for Intel Macs

            ### Auto-Updates

            This release supports automatic updates. If you're running a previous version, you'll be notified when this update is available and can install it directly from the app.

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ github.event.before }}...${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

      - name: List generated files
        run: ls -R src-tauri/target/ || true
